apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base


patches:
  - target:
      kind: IngressRoute
      name: technight-web-route
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`acc.technight.developers.nl`)

images:
  - name: larsnieuwenhuizen/technight-php
    newTag: "pr-1"
